export const SUGGESTION_TEMPLATES = {
  conflictDescription: [
    "Communication breakdown between team members",
    "Disagreement over project priorities and deadlines",
    "Personality clash affecting work collaboration",
    "Misunderstanding about roles and responsibilities",
    "Conflict over resource allocation and budget",
    "Different working styles causing friction",
    "Disagreement about decision-making process",
    "Conflict arising from unclear expectations",
  ],
  thoughts: [
    "I feel like my concerns aren't being heard",
    "I believe we have different priorities and goals",
    "I think there's a misunderstanding about expectations",
    "I feel frustrated because I'm not getting the support I need",
    "I believe we need better communication protocols",
    "I think we should focus on finding common ground",
    "I feel like we're not working as a team",
    "I believe we need to clarify our roles and responsibilities",
  ],
  assertiveApproach: [
    "I would like to discuss this issue openly and find a solution together",
    "I understand your perspective, and I'd like to share mine as well",
    "I believe we can work through this by focusing on our common goals",
    "I'd appreciate it if we could find a compromise that works for both of us",
    "I think we should take some time to understand each other's needs better",
    "I would like to establish clear communication guidelines going forward",
    "I believe we can resolve this by being honest about our concerns",
    "I'd like to work together to prevent this issue from happening again",
  ],
  activatingEvent: [
    "During the team meeting on [date], there was a disagreement about...",
    "The incident occurred when [person] said/did [specific action]",
    "The conflict started when we received conflicting instructions about...",
    "The issue arose during a project review when [specific event] happened",
    "The disagreement began when [person] made a decision without consulting...",
    "The conflict started during a discussion about [topic] when [specific action]",
    "The incident occurred in [location] when [specific event] took place",
    "The disagreement began when we had different interpretations of...",
  ],
  miracleQuestion: [
    "We would be communicating openly and honestly with each other",
    "We would have clear expectations and roles defined",
    "We would be working together as a cohesive team",
    "We would have regular check-ins to prevent future conflicts",
    "We would respect each other's perspectives and working styles",
    "We would have established protocols for handling disagreements",
    "We would be focused on our shared goals and objectives",
    "We would have a positive and collaborative working relationship",
  ],
  solutions: [
    "Establish weekly check-in meetings to discuss progress and concerns",
    "Create a shared document outlining roles and responsibilities",
    "Implement a conflict resolution protocol for future disagreements",
    "Schedule regular team-building activities to improve relationships",
    "Set up a communication channel for immediate issue resolution",
    "Create a feedback system for ongoing improvement",
    "Establish clear decision-making processes and criteria",
    "Develop a shared understanding of project goals and priorities",
  ],
  actionSteps: [
    "Schedule a follow-up meeting in 2 weeks to review progress",
    "Create a shared action plan document with specific deadlines",
    "Assign specific responsibilities to each party with clear timelines",
    "Establish a communication protocol for ongoing updates",
    "Set up regular check-ins to monitor progress and address issues",
    "Create a feedback mechanism for continuous improvement",
    "Document lessons learned to prevent future conflicts",
    "Establish accountability measures and success metrics",
  ],
};

export const HELP_TEXTS = {
  conflictDescription: {
    title: "Describing the Conflict",
    tips: [
      "Focus on observable facts, not interpretations",
      "Include when and where the conflict occurred",
      "Describe specific actions or events that happened",
      "Avoid blame or judgmental language",
      "Ensure both parties agree on this description",
    ],
  },
  thoughts: {
    title: "Expressing Your Thoughts",
    tips: [
      "Be honest about your beliefs and assumptions",
      "Use 'I think' or 'I believe' statements",
      "Avoid making assumptions about the other person's intentions",
      "Focus on your own perspective and feelings",
      "Be specific about what you think happened",
    ],
  },
  assertiveApproach: {
    title: "Assertive Communication",
    tips: [
      "Use 'I' statements to express your needs",
      "Be respectful and considerate of the other person",
      "Focus on finding solutions, not assigning blame",
      "Be clear about what you want to achieve",
      "Listen actively to the other person's response",
    ],
  },
  miracleQuestion: {
    title: "The Miracle Question",
    tips: [
      "Imagine waking up tomorrow with the conflict completely resolved",
      "Describe what would be different in your relationship",
      "Focus on positive changes and improvements",
      "Be specific about what you would see, hear, or experience",
      "Think about how both parties would feel and behave",
    ],
  },
  solutions: {
    title: "Finding Solutions",
    tips: [
      "Focus on solutions that work for both parties",
      "Be creative and open to new ideas",
      "Consider both short-term and long-term solutions",
      "Think about what each person can do differently",
      "Aim for win-win outcomes whenever possible",
    ],
  },
};
